# Validation of semantic association using data from Federmeier & Kutas 1999
Plotting and exploration of semantic association values of target words from Federmeier & Kutas (1999) extracted from different definitions of semantic assocition.

```{r}
library(tidytable)
library(ggplot2)

setwd("cmcl26")
```

```{r}
df <- read.csv("results/federmeier_kutas_validation.csv")
```

```{r}
df |>
    group_by(
        language,
        embedding_model,
        context,
        n_sentences,
        n_words
    ) |>
    summarize(
        "expected" = mean(expected),
        "within" = mean(within),
        "between" = mean(between),
        "unexpected" = mean(unexpected)
    )
```

## plots
```{r}
df_long <- df |>
    mutate(
        context_name = context,
        context_name = ifelse(
            !is.na(n_words), paste0(n_words, " word(s)"), context_name
        ),
        context_name = ifelse(
            !is.na(n_sentences),
            paste0(n_sentences, " sentences"), context_name
        )
    ) |>
    pivot_longer(
        cols = c(expected, within, between, unexpected),
        names_to = "measure",
        values_to = "value"
    )
```

```{r}
lan <- "en"

df_long |>
    filter(language == lan) |>
    group_by(
        model_name, embedding_model, context_name, measure
    ) |>
    summarize(
        mean = mean(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
    ) |>
    mutate(
        target = factor(
            measure,
            levels = c("expected", "within", "between", "unexpected")
        ),
        context_name_f = factor(
            context_name,
            levels = c(
                "original", "long",
                "5 sentences",
                "2 word(s)", "1 word(s)"
            )
        )
    ) |>
    filter(embedding_model != "WordEmbeddingWindowed") |>
    ggplot(aes(x = context_name_f, color = target, group = target)) +
    geom_point(
        aes(y = mean),
        position = position_dodge(width = 0.3),
        size = 2
    ) +
    geom_errorbar(
        aes(ymin = mean - sd, ymax = mean + sd),
        width = 0.15,
        position = position_dodge(width = 0.3)
    ) +
    scale_colour_manual(
        values = c(
            expected = "blue",
            within = "firebrick2",
            between = "purple",
            unexpected = "orange"
        ),
        breaks = c("expected", "within", "between", "unexpected")
    ) +
    facet_wrap(embedding_model ~ model_name, scale = "free", ncol = 2) +
    labs(x = "context") +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(file.path("figs", "sem_association_all.png"), height = 10, width = 7)
```
```{r}
lan <- "en"

df_long |>
    filter(language == lan) |>
    mutate(measure_f = factor(
        measure,
        levels = c("expected", "within", "between", "unexpected")
    )) |>
    filter(context_name == "original") |>
    ggplot(aes(color = measure_f)) +
    geom_density(aes(x = value)) +
    scale_colour_manual(
        values = c(
            expected = "blue",
            within = "firebrick2",
            between = "purple",
            unexpected = "orange"
        ),
        breaks = c("expected", "within", "between", "unexpected")
    ) +
    facet_wrap(embedding_model ~ model_name, scale = "free") +
    theme_minimal()
```