# Implementation disagreement
Modeling the disagreement between the implementations of semantic association.

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(lmerTest)

setwd("experiment3")
```

## Read data
```{r}
data_path <- file.path("..", "experiment2", "results")

tanner_df <- read.csv(file.path(data_path, "tanner_semantic_association.csv")) |>
    filter(Acceptability == "Gram") |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(implementation, model) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

ucl_df <- read.csv(file.path(data_path, "ucl_semantic_association.csv")) |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(implementation, model) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

derco_df <- read.csv(file.path(data_path, "derco_semantic_association.csv")) |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(article_n, full_implementation) |>
    mutate(
        context_length = ifelse(str_detect(implementation, "sentences1"), "Sentence(N=1)", "All")
    ) |>
    ungroup() |>
    group_by(full_implementation) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

# content words pos tags
content_pos <- c("NOUN", "VERB", "ADJ", "ADV")
```

## Modeling variance
Tanner
```{r}
data <- tanner_df |>
    filter(pos %in% content_pos) |>
    group_by(id, word_n, pos, s_lp) |>
    summarize(
        variance = var(s_sem, na.rm = TRUE)
    )

fit <- lmer(variance ~ word_n + pos + s_lp + (1 | id), data = data)
summary(fit)
```

UCL
```{r}
data <- ucl_df |>
    filter(pos %in% content_pos) |>
    group_by(id, word_n, pos, s_lp) |>
    summarize(
        variance = var(s_sem, na.rm = TRUE)
    )

fit <- lmer(variance ~ word_n + pos + s_lp + (1 | id), data = data)
summary(fit)
```

DERCo: All
```{r}
data <- derco_df |>
    filter(context_length == "All") |>
    filter(pos %in% content_pos) |>
    group_by(article_n, word_n, pos, s_lp) |>
    summarize(
        variance = var(s_sem, na.rm = TRUE)
    )

fit <- lmer(variance ~ word_n + pos + s_lp + (1 | article_n), data = data)
summary(fit)
```

DERCo: Sentence(N=1)
```{r}
data <- derco_df |>
    filter(context_length == "Sentence(N=1)") |>
    filter(pos %in% content_pos) |>
    group_by(article_n, word_n, pos, s_lp) |>
    summarize(
        variance = var(s_sem, na.rm = TRUE)
    )

fit <- lmer(variance ~ word_n + pos + s_lp + (1 | article_n), data = data)
summary(fit)
```

## Modeling scaled values
Tanner
```{r}
data <- tanner_df |>
    filter(pos %in% content_pos)

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:word_n + implementation:pos + implementation:s_lp +
        (0 + implementation | id) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data <- tanner_df |>
    filter(pos %in% content_pos)

quantiles <- quantile(data$s_lp, na.rm = TRUE)

data <- data |>
    mutate(
        q_lp = factor(case_when(
            s_lp <= quantiles[2] ~ "Q25",
            s_lp > quantiles[2] & s_lp <= quantiles[3] ~ "Q50",
            s_lp > quantiles[3] & s_lp <= quantiles[4] ~ "Q75",
            s_lp > quantiles[4] ~ "Q100",
        ), levels = c("Q25", "Q50", "Q75", "Q100"))
    )

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:q_lp +
        (0 + implementation | id) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data |>
    ggplot(aes(x = s_lp, y = s_sem, color = model)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(. ~ implementation) +
    scale_color_manual(
        values = c(
            "orange2", "orange4", "steelblue2",
            "seagreen2", "seagreen4", "orchid2",
            "orchid4", "steelblue4"
        )
    ) +
    theme_bw() +
    labs(x = "Scaled log-probability", y = "Scaled semantic association", title = "Tanner") +
    theme(legend.position = "bottom")
```

UCL
```{r}
data <- ucl_df |>
    filter(pos %in% content_pos)

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:word_n + implementation:pos + implementation:s_lp +
        (0 + implementation | id) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data <- ucl_df |>
    filter(pos %in% content_pos)

quantiles <- quantile(data$s_lp, na.rm = TRUE)

data <- data |>
    mutate(
        q_lp = factor(case_when(
            s_lp <= quantiles[2] ~ "Q25",
            s_lp > quantiles[2] & s_lp <= quantiles[3] ~ "Q50",
            s_lp > quantiles[3] & s_lp <= quantiles[4] ~ "Q75",
            s_lp > quantiles[4] ~ "Q100",
        ), levels = c("Q25", "Q50", "Q75", "Q100"))
    )

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:q_lp +
        (0 + implementation | id) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data |>
    ggplot(aes(x = s_lp, y = s_sem, color = model)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(. ~ implementation) +
    scale_color_manual(
        values = c(
            "orange2", "orange4", "steelblue2",
            "seagreen2", "seagreen4", "orchid2",
            "orchid4", "steelblue4"
        )
    ) +
    theme_bw() +
    labs(x = "Scaled log-probability", y = "Scaled semantic association", title = "UCL") +
    theme(legend.position = "bottom")
```

DERCo: All
```{r}
data <- derco_df |>
    filter(context_length == "All") |>
    filter(pos %in% content_pos)

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:word_n + implementation:pos + implementation:s_lp +
        (0 + implementation | article_n) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data <- derco_df |>
    filter(context_length == "All") |>
    filter(pos %in% content_pos)

quantiles <- quantile(data$s_lp, na.rm = TRUE)

data <- data |>
    mutate(
        q_lp = factor(case_when(
            s_lp <= quantiles[2] ~ "Q25",
            s_lp > quantiles[2] & s_lp <= quantiles[3] ~ "Q50",
            s_lp > quantiles[3] & s_lp <= quantiles[4] ~ "Q75",
            s_lp > quantiles[4] ~ "Q100",
        ), levels = c("Q25", "Q50", "Q75", "Q100"))
    )

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:q_lp +
        (0 + implementation | article_n) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data |>
    ggplot(aes(x = s_lp, y = s_sem, color = model)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(. ~ implementation) +
    scale_color_manual(
        values = c(
            "orange2", "orange4", "steelblue2",
            "seagreen2", "seagreen4", "orchid2",
            "orchid4", "steelblue4"
        )
    ) +
    theme_bw() +
    labs(x = "Scaled log-probability", y = "Scaled semantic association", title = "DERCo") +
    theme(legend.position = "bottom")
```

DERCo: Sentence(N=1)
```{r}
data <- derco_df |>
    filter(context_length == "Sentence(N=1)") |>
    filter(pos %in% content_pos)

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:word_n + implementation:pos + implementation:s_lp +
        (0 + implementation | article_n) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data <- derco_df |>
    filter(context_length == "Sentence(N=1)") |>
    filter(pos %in% content_pos)

quantiles <- quantile(data$s_lp, na.rm = TRUE)

data <- data |>
    mutate(
        q_lp = factor(case_when(
            s_lp <= quantiles[2] ~ "Q25",
            s_lp > quantiles[2] & s_lp <= quantiles[3] ~ "Q50",
            s_lp > quantiles[3] & s_lp <= quantiles[4] ~ "Q75",
            s_lp > quantiles[4] ~ "Q100",
        ), levels = c("Q25", "Q50", "Q75", "Q100"))
    )

fit <- lmer(
    s_sem ~ 0 + implementation + implementation:q_lp +
        (0 + implementation | article_n) +
        (0 + implementation | model),
    data = data
)
summary(fit)
```

```{r}
data |>
    ggplot(aes(x = s_lp, y = s_sem, color = model)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(. ~ implementation) +
    scale_color_manual(
        values = c(
            "orange2", "orange4", "steelblue2",
            "seagreen2", "seagreen4", "orchid2",
            "orchid4", "steelblue4"
        )
    ) +
    theme_bw() +
    labs(
        x = "Scaled log-probability", y = "Scaled semantic association",
        title = "DERCo", subtitle = "Sentence(N=1)"
    ) +
    theme(legend.position = "bottom")
```