# Qualitative inspection of semantic association in specific sentences

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(patchwork)

setwd("experiment2")
```

## load data
```{r}
tanner_df <- read.csv(file.path("results", "tanner_semantic_association.csv")) |>
    filter(Acceptability == "Gram") |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(implementation, model) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup()

derco_df <- read.csv(file.path("results", "derco_semantic_association.csv")) |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(article_n, full_implementation) |>
    mutate(
        sentence_n = cumsum(
            lag(str_detect(target, "\\.$"), default = FALSE)
        )
    ) |>
    ungroup() |>
    group_by(full_implementation) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup()
```

## Tanner
### sentences with highest/lowest semantic association
```{r}
print_sentences_tanner <- function(df) {
    for (i in seq_len(nrow(df))) {
        imp <- df[i, ]$full_implementation
        sentence_id <- df[i, ]$sentence_id
        word <- df[i, ]$word

        sentence <- tanner_df |>
            filter(id == sentence_id) |>
            pull(word) |>
            unique() |>
            paste(collapse = " ")

        print(
            paste0(
                "Implementation: ", imp,
                ", id ", sentence_id,
                ", Word number: ", word
            )
        )
        print(sentence)
        print("---")
    }
}
```

```{r}
low_sem <- tanner_df |>
    filter(!is.na(semantic_association)) |>
    group_by(full_implementation) |>
    filter(semantic_association == min(semantic_association)) |>
    summarize(
        "sentence_id" = id,
        "word" = word_n
    )

print_sentences(low_sem)
```

```{r}
high_sem <- tanner_df |>
    filter(!is.na(semantic_association)) |>
    group_by(full_implementation) |>
    filter(semantic_association == max(semantic_association)) |>
    summarize(
        "sentence_id" = id,
        "word" = word_n
    )

print_sentences(high_sem)
```

### visualization
Choose sentence
```{r}
sentence_ids <- tanner_df |>
    pull(id) |>
    unique()
sentence_id <- sentence_ids[2]

# sentence_id <- 5762

df <- tanner_df |>
    filter(id == sentence_id)
```

Print sentences
```{r}
df |>
    pull(word) |>
    unique() |>
    paste(collapse = " ")
```

Heatmap
```{r}
save_fig <- FALSE

words_df <- df |>
    group_by(word_n) |>
    summarize("word" = unique(word))

p <- df |>
    ggplot(aes(x = word_n, y = full_implementation, fill = s_sem)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey95",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    scale_x_continuous(
        breaks = words_df$word_n,
        labels = words_df$word,
    ) +
    labs(
        x = "",
        y = ""
    ) +
    theme_classic() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.line = element_blank(),
        axis.ticks.y = element_blank()
    )

if (save_fig) {
    ggsave(
        file.path(
            "figs", "example_sentences",
            paste0("tanner_example_sentence", sentence_id, ".png")
        ),
        height = 4, width = 10
    )
} else {
    p + theme(aspect.ratio = .5)
}
```

## DERCo
### sentences with highest/lowest semantic association
```{r}
print_sentences_derco <- function(df) {
    for (i in seq_len(nrow(df))) {
        imp <- df[i, ]$full_implementation
        article_id <- df[i, ]$article_id
        sentence_id <- df[i, ]$sentence_id
        word <- df[i, ]$word

        sentence <- derco_df |>
            filter(article_n == article_id) |>
            filter(sentence_n == sentence_id) |>
            pull(target) |>
            unique() |>
            paste(collapse = " ")

        print(
            paste0(
                "Implementation: ", imp,
                ", article ", article_id,
                ", sentence ", sentence_id,
                ", Word number: ", word
            )
        )
        print(sentence)
        print("---")
    }
}
```

```{r}
low_sem <- derco_df |>
    filter(!str_detect(full_implementation, "sentences1")) |>
    filter(!is.na(semantic_association)) |>
    group_by(full_implementation) |>
    filter(semantic_association == min(semantic_association)) |>
    summarize(
        "article_id" = article_n,
        "sentence_id" = sentence_n,
        "word" = word_n
    )

print_sentences_derco(low_sem)
```

```{r}
high_sem <- derco_df |>
    filter(!str_detect(full_implementation, "sentences1")) |>
    filter(!is.na(semantic_association)) |>
    group_by(full_implementation) |>
    filter(semantic_association == max(semantic_association)) |>
    summarize(
        "article_id" = article_n,
        "sentence_id" = sentence_n,
        "word" = word_n
    )

print_sentences_derco(high_sem)
```

### visualization
Choose sentence
```{r}
article_id <- 3
sentence_id <- 14

df <- derco_df |>
    filter(article_n == article_id) |>
    filter(sentence_n == sentence_id)
```

Print sentences
```{r}
df |>
    pull(target) |>
    unique() |>
    paste(collapse = " ")
```

Heatmap
```{r}
save_fig <- FALSE

words_df <- df |>
    group_by(word_n) |>
    summarize("word" = unique(target))

p <- df |>
    filter(!str_detect(implementation, "sentences1")) |>
    ggplot(aes(x = word_n, y = full_implementation, fill = s_sem)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey95",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    scale_x_continuous(
        breaks = words_df$word_n,
        labels = words_df$word,
    ) +
    labs(
        x = "",
        y = ""
    ) +
    theme_classic() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.line = element_blank(),
        axis.ticks.y = element_blank()
    )

if (save_fig) {
    ggsave(
        file.path(
            "figs", "example_sentences",
            paste0(
                "derco_example_sentence", sentence_id,
                "_article", article_id, ".png"
            )
        ),
        height = 4, width = 10
    )
} else {
    p + theme(aspect.ratio = .5)
}
```
