# Model comparison with the Savage-Dickey ratio

```{r}
library(tidytable)
library(stringr)
library(brms)
library(polspline)
library(ggplot2)

setwd("cmcl26")

source(file.path("src", "rename_implementations.r"))

options(mc.cores = parallel::detectCores())

models_path <- file.path("analysis", "brms_models")
```

## helper functions
```{r}
# returns the sd for the prior of beta_2 (b_s_sem)
get_sem_prior_sd <- function(fit) {
  priors_b <- fit$prior[fit$prior$class == "b", c("prior", "coef")]
  prior_b_sem <- priors_b[priors_b$coef == "s_sem", "prior"]

  if (prior_b_sem == "") {
    # then all priors of beta is the same
    prior_b_sem <- priors_b[priors_b$coef == "", "prior"]
  }

  prior_b_sem_sd <- str_extract(prior_b_sem, "(?<=, )[0-9.]+")
  return(as.numeric(prior_b_sem_sd))
}

# get name of implementation from model name
get_implementation <- function(model_name) {
  str_extract(model_name, "(?<=semantic_association_).*?(?=\\.rds|_bsemprior)")
}
```

## calculate Savage-Dickey ratio of s_sem beta estimate
```{r}
rm(sd_df)

dep_vars <- c("rt", "n400")
for (dep_var in dep_vars) {
  print(dep_var)
  sem_model_names <- list.files(models_path,
    full.names = FALSE,
    pattern = paste0(dep_var, "_semantic_association_.*\\.rds$")
  )

  for (model_name in sem_model_names) {
    print(model_name)
    sem_m <- readRDS(file.path(models_path, model_name))

    prior_sd <- get_sem_prior_sd(sem_m)

    # savage-dickey ratio
    posterior_sem <- sem_m |>
      as_draws_df() |>
      pull(b_s_sem)
    fit_posterior <- logspline(posterior_sem)
    posterior <- dlogspline(0, fit_posterior) # Height of the posterior at 0
    prior <- dnorm(0, mean = 0, sd = prior_sd) # Height of the prior at 0
    BF01 <- posterior / prior


    tmp_df <- data.frame(
      "posterior" = posterior,
      "prior" = prior,
      "BF01" = BF01,
      "dep_var" = dep_var,
      "prior_sd" = prior_sd,
      "model_name" = model_name,
      "implementation" = get_implementation(model_name)
    )

    if (exists("sd_df")) {
      sd_df <- rbind(tmp_df, sd_df)
    } else {
      sd_df <- tmp_df
    }
  }
}
```

## plot
```{r}
# Custom breaks
custom_breaks <- c(100, 30, 10, 3, 1, 1 / 3, 1 / 10)
custom_labels <- c("100", "30", "10", "3", "1", "1/3", "1/10")

sd_df |>
  mutate("dep_var" = case_when(
    dep_var == "rt" ~ "Reading Times",
    dep_var == "n400" ~ "N400"
  )) |>
  mutate("implementation" = rename_implementations(implementation)) |>
  mutate(
    "implementation" = factor(implementation, levels = c(
      "SE, All", "SE, Sentence(N=1)",
      "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
      "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
      "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
    ))
  ) |>
  mutate(model_type = case_when(
    str_detect(implementation, "SE") ~ "SE",
    str_detect(implementation, "CWE") ~ "CWE",
    str_detect(implementation, "WE") ~ "WE"
  )) |>
  mutate("model_type" = factor(model_type, levels = c("SE", "WE", "CWE"))) |>
  ggplot(aes(
    x = implementation,
    color = model_type,
    shape = as.factor(prior_sd)
  )) +
  geom_point(aes(y = BF01), size = 2) +
  geom_hline(aes(yintercept = 1), linetype = "dotted") +
  scale_y_log10(
    breaks = custom_breaks,
    labels = custom_labels,
    limits = c(1 / 10, 140)
  ) +
  theme_minimal() +
  facet_wrap(. ~ dep_var, ncol = 1) +
  scale_shape_manual(values = c(17, 4, 16, 15, 3, 18)) +
  scale_color_manual(values = c("firebrick", "steelblue2", "steelblue4")) +
  # scale_color_manual(values = c("steelblue", "firebrick2", "firebrick4")) +
  labs(x = "", color = "Embeddings", shape = "SD of prior") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    # legend.position = "bottom"
  )

ggsave(file.path("figs", "Savage-Dickey.pdf"), width = 5, height = 5)
```
