# Correlation in the estimated values of semantic association accross embedding models

```{r}
library(tidytable)
library(dplyr)
library(stringr)
library(ggplot2)
library(reshape2)
library(patchwork)

setwd("extra_experiments")
```

## Read data
```{r}
data_path <- file.path("..", "experiment2", "results")

tanner_df <- read.csv(file.path(data_path, "tanner_semantic_association.csv")) |>
    filter(Acceptability == "Gram") |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(implementation, model) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

ucl_df <- read.csv(file.path(data_path, "ucl_semantic_association.csv")) |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(implementation, model) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

derco_df <- read.csv(file.path(data_path, "derco_semantic_association.csv")) |>
    mutate(full_implementation = paste(implementation, model, sep = "_")) |>
    group_by(article_n, full_implementation) |>
    mutate(
        context_length = ifelse(str_detect(implementation, "sentences1"), "Sentence(N=1)", "Sentence(N=10)")
    ) |>
    ungroup() |>
    group_by(full_implementation) |>
    mutate(s_sem = scale(semantic_association)) |>
    ungroup() |>
    filter(model != "Gameselo/STS-multilingual-mpnet-base-v2")

# content words pos tags
content_pos <- c("NOUN", "VERB", "ADJ", "ADV")
```

## Correlations: Tanner
all words
```{r}
cor_matrix <- tanner_df |>
    select(id, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

only content words
```{r}
cor_matrix <- tanner_df |>
    filter(pos %in% content_pos) |>
    select(id, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom"
    ) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

by POS tag (only content words)
```{r}
for (n in 1:4) {
    cor_matrix <- tanner_df |>
        filter(pos == content_pos[n]) |>
        select(id, word_n, semantic_association, s_lp, full_implementation) |>
        pivot_wider(
            names_from = full_implementation,
            values_from = semantic_association,
            names_prefix = "semantic_association_"
        ) |>
        select(starts_with("semantic_association"), "s_lp", "word_n") |>
        cor(use = "pairwise.complete.obs")

    # Remove prefix
    prefix <- "^semantic_association_"
    colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
    rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

    matrix_names <- colnames(cor_matrix)
    name_order <- order(
        case_when(
            str_starts(matrix_names, "WE") ~ 1L,
            str_starts(matrix_names, "CWE") ~ 2L,
            str_starts(matrix_names, "SE") ~ 3L,
            TRUE ~ 4L
        ),
        matrix_names
    )

    cor_matrix <- cor_matrix[name_order, name_order]


    melted <- melt(cor_matrix)

    p <- ggplot(melted, aes(Var1, Var2, fill = value)) +
        geom_tile() +
        geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
        scale_fill_gradient2(
            low = "blue", high = "red", mid = "white",
            midpoint = 0, limit = c(-1, 1)
        ) +
        theme_minimal() +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            legend.position = "bottom"
        ) +
        labs(x = "", y = "", fill = "Correlation", title = content_pos[n])

    if (n == 1) {
        p1 <- p
    } else if (n == 2) {
        p2 <- p
    } else if (n == 3) {
        p3 <- p
    } else if (n == 4) {
        p4 <- p
    }
}

(p1 + p2) / (p3 + p4) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom") &
    plot_annotation(title = "Tanner (2019)")

ggsave(file.path("figs", "tanner_correlations_pos.png"), width = 15, height = 15)
```

## Correlations: UCL
all words
```{r}
cor_matrix <- ucl_df |>
    select(id, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

only content words
```{r}
cor_matrix <- ucl_df |>
    filter(pos %in% content_pos) |>
    select(id, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom"
    ) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

by POS tag (only content words)
```{r}
for (n in 1:4) {
    cor_matrix <- ucl_df |>
        filter(pos == content_pos[n]) |>
        select(id, word_n, semantic_association, s_lp, full_implementation) |>
        pivot_wider(
            names_from = full_implementation,
            values_from = semantic_association,
            names_prefix = "semantic_association_"
        ) |>
        select(starts_with("semantic_association"), "s_lp", "word_n") |>
        cor(use = "pairwise.complete.obs")

    # Remove prefix
    prefix <- "^semantic_association_"
    colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
    rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

    matrix_names <- colnames(cor_matrix)
    name_order <- order(
        case_when(
            str_starts(matrix_names, "WE") ~ 1L,
            str_starts(matrix_names, "CWE") ~ 2L,
            str_starts(matrix_names, "SE") ~ 3L,
            TRUE ~ 4L
        ),
        matrix_names
    )

    cor_matrix <- cor_matrix[name_order, name_order]


    melted <- melt(cor_matrix)

    p <- ggplot(melted, aes(Var1, Var2, fill = value)) +
        geom_tile() +
        geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
        scale_fill_gradient2(
            low = "blue", high = "red", mid = "white",
            midpoint = 0, limit = c(-1, 1)
        ) +
        theme_minimal() +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            legend.position = "bottom"
        ) +
        labs(x = "", y = "", fill = "Correlation", title = content_pos[n])

    if (n == 1) {
        p1 <- p
    } else if (n == 2) {
        p2 <- p
    } else if (n == 3) {
        p3 <- p
    } else if (n == 4) {
        p4 <- p
    }
}

(p1 + p2) / (p3 + p4) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom") &
    plot_annotation(title = "UCL")

ggsave(file.path("figs", "ucl_correlations_pos.png"), width = 15, height = 15)
```

## Correlations: DERCo
all words
```{r}
cor_matrix <- derco_df |>
    filter(context_length == "Sentence(N=10)") |>
    select(article_n, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

only content words
```{r}
cor_matrix <- derco_df |>
    filter(context_length == "Sentence(N=10)") |>
    filter(pos %in% content_pos) |>
    select(article_n, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
cor_matrix
```

```{r}
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom"
    ) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

by POS tag (only content words)
```{r}
for (n in 1:4) {
    cor_matrix <- derco_df |>
        filter(context_length == "Sentence(N=10)") |>
        filter(pos == content_pos[n]) |>
        select(article_n, word_n, semantic_association, s_lp, full_implementation) |>
        pivot_wider(
            names_from = full_implementation,
            values_from = semantic_association,
            names_prefix = "semantic_association_"
        ) |>
        select(starts_with("semantic_association"), "s_lp", "word_n") |>
        cor(use = "pairwise.complete.obs")

    # Remove prefix
    prefix <- "^semantic_association_"
    colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
    rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

    matrix_names <- colnames(cor_matrix)
    name_order <- order(
        case_when(
            str_starts(matrix_names, "WE") ~ 1L,
            str_starts(matrix_names, "CWE") ~ 2L,
            str_starts(matrix_names, "SE") ~ 3L,
            TRUE ~ 4L
        ),
        matrix_names
    )

    cor_matrix <- cor_matrix[name_order, name_order]


    melted <- melt(cor_matrix)

    p <- ggplot(melted, aes(Var1, Var2, fill = value)) +
        geom_tile() +
        geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
        scale_fill_gradient2(
            low = "blue", high = "red", mid = "white",
            midpoint = 0, limit = c(-1, 1)
        ) +
        theme_minimal() +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            legend.position = "bottom"
        ) +
        labs(x = "", y = "", fill = "Correlation", title = content_pos[n])

    if (n == 1) {
        p1 <- p
    } else if (n == 2) {
        p2 <- p
    } else if (n == 3) {
        p3 <- p
    } else if (n == 4) {
        p4 <- p
    }
}

(p1 + p2) / (p3 + p4) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom") &
    plot_annotation(title = "DERCo")

ggsave(file.path("figs", "derco_correlations_pos.png"), width = 15, height = 15)
```

Sentences(N=1) and Sentence(N=10)
```{r}
implementation_substring <- "SE"

cor_matrix <- derco_df |>
    filter(str_detect(full_implementation, implementation_substring)) |>
    select(article_n, word_n, semantic_association, s_lp, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "s_lp", "word_n") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]

melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

