# Plots of semantic association for the TiNT data

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(patchwork)
library(ggtext)

source(file.path("src", "rename_implementations.r"))
```

## load data
```{r}
tint_df <- read.csv(file.path("data", "tint_stim.csv")) |>
    select(-X) |>
    filter(document_id < 10) |>
    mutate(content_word = ifelse(
        pos %in% c("NOUN", "VERB", "ADJ", "ADV"),
        TRUE, FALSE
    )) |>
    # make sentence_number col
    group_by(document_id) |>
    mutate(
        new_sentence_start = grepl("\\.$", lag(word)),
        sentence_number = cumsum(new_sentence_start) + 1
    ) |>
    select(-new_sentence_start)

sem_df <- read.csv(
    file.path("results", "tint_semantic_association.csv")
) |>
    left_join(tint_df)
```

## Plot density
```{r}
sem_df |>
    mutate(across(starts_with("semantic_association"), scale)) |>
    pivot_longer(
        cols = c(starts_with("semantic_association")),
        names_to = "implementation",
        values_to = "value"
    ) |>
    mutate(
        "implementation" = rename_implementations(implementation)
    ) |>
    mutate(
        "implementation" = factor(
            implementation,
            levels = c(
                "SE, All", "SE, Sentence(N=1)",
                "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
                "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
                "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
            )
        )
    ) |>
    ggplot() +
    geom_density(aes(x = value, fill = implementation), alpha = .5) +
    facet_wrap(. ~ implementation, ncol = 2) +
    theme_minimal() +
    scale_fill_manual(values = c(
        "firebrick1", "firebrick4",
        "steelblue1", "steelblue2", "steelblue3", "steelblue4",
        "slateblue1", "slateblue2", "slateblue3", "slateblue4"
    )) +
    theme(legend.position = "bottom")
```

## Explore difference
Words with largest difference in semantic asssociation across implementations
```{r}
sem_df |>
    mutate(
        diff = semantic_association_SentenceEmbedding - semantic_association_WordEmbedding
    ) |>
    mutate(s_diff = scale(diff)) |>
    filter(s_diff > 2.5) |>
    select(
        word, number_word, sentence_number, document_id, content_word, s_diff
    ) |>
    print(n = 50)
```

Word with largest semantic association values
```{r}
sem_df |>
    filter(content_word) |>
    mutate(
        s_se = scale(semantic_association_SentenceEmbedding),
        s_we = scale(semantic_association_WordEmbedding)
    ) |>
    filter(s_we > 2) |>
    select(
        word, number_word, sentence_number, document_id, content_word, s_we
    ) |>
    print(n = 50)
```

## visualization
Choose sentences
```{r}
doc_id <- 1
sentences <- c(5:6)

df <- sem_df |>
    filter(document_id == doc_id & sentence_number %in% sentences)

df_long <- df |>
    mutate(across(starts_with("semantic_association"), scale)) |>
    pivot_longer(
        cols = c(starts_with("semantic_association"), s_lp, s_freq),
        names_to = "implementation",
        values_to = "value"
    ) |>
    mutate(
        "implementation" = rename_implementations(implementation)
    ) |>
    mutate(implementation = case_when(
        implementation == "s_freq" ~ "Zipf Frequency",
        implementation == "s_lp" ~ "Log Probability",
        .default = implementation
    )) |>
    mutate(
        "implementation" = factor(
            implementation,
            levels = c(
                "Log Probability", "Zipf Frequency",
                "SE, All", "SE, Sentence(N=1)",
                "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
                "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
                "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
            )
        )
    )
```

Print sentences
```{r}
df |>
    pull(word) |>
    paste(collapse = " ")
```

Words and semantic values
```{r}
df |>
    mutate(across(starts_with("semantic_association"), scale)) |>
    select(word, starts_with("semantic_association")) |>
    rename_with(~ str_remove(., "^semantic_association_")) |>
    t() |>
    as.data.frame()
```

Heatmap
```{r}
save_fig <- FALSE

p <- df_long |>
    # mutate(value = ifelse(content_word, value, NA)) |>
    ggplot(aes(x = number_word, y = implementation, fill = value)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey95",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    scale_x_continuous(
        breaks = df$number_word,
        labels = df$word,
    ) +
    labs(
        x = "",
        y = ""
    ) +
    theme_classic() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.line = element_blank(),
        axis.ticks.y = element_blank()
    )

if (save_fig) {
    ggsave(
        file.path(
            "figs",
            paste0("example_sentences", sentences[1], "-", sentences[2], "doc", doc_id, ".png")
        ),
        height = 4, width = 10
    )
} else {
    p + theme(aspect.ratio = .5)
}
```

Line plot
```{r}
df_long |>
    ggplot(aes(x = number_word, y = value, color = implementation)) +
    geom_line(linewidth = 1) +
    geom_point(size = 2) +
    scale_x_continuous(
        breaks = df$number_word,
        labels = df$word,
    ) +
    labs(
        x = "Word",
        y = "Semantic Association",
        color = "Implementation"
    ) +
    theme_minimal() +
    scale_color_manual(values = c(
        "grey50", "grey70",
        "firebrick1", "firebrick4",
        "steelblue1", "steelblue2", "steelblue3", "steelblue4",
        "slateblue1", "slateblue2", "slateblue3", "slateblue4"
    )) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom"
    )
```

```{r}
# Faceted plot (separate panel for each semantic association implementation)
ggplot(df_long, aes(x = number_word, y = value)) +
    geom_line(linewidth = 1, color = "steelblue") +
    geom_point(size = 2, color = "steelblue") +
    facet_wrap(~implementation, ncol = 1, scales = "free_y") +
    scale_x_continuous(
        breaks = df$number_word,
        labels = df$word
    ) +
    labs(
        x = "Word",
        y = "Value"
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Heat map of sentence pairs for paper
```{r}
doc_id_a <- 1
sentences_a <- c(5:6)
doc_id_b <- 6
sentences_b <- c(10:11)

df <- sem_df |>
    filter(
        (document_id == doc_id_a & sentence_number %in% sentences_a) |
            (document_id == doc_id_b & sentence_number %in% sentences_b)
    ) |>
    mutate(
        "sentences_id" = case_when(
            document_id == doc_id_a ~ "A",
            document_id == doc_id_b ~ "B"
        )
    )

df_long <- df |>
    mutate(across(starts_with("semantic_association"), scale)) |>
    pivot_longer(
        cols = c(starts_with("semantic_association"), s_lp, s_freq),
        names_to = "implementation",
        values_to = "value"
    ) |>
    mutate(
        "implementation" = rename_implementations(implementation)
    ) |>
    mutate(implementation = case_when(
        implementation == "s_freq" ~ "Zipf Frequency",
        implementation == "s_lp" ~ "Log Probability",
        .default = implementation
    )) |>
    mutate(
        "implementation" = factor(
            implementation,
            levels = c(
                "Log Probability", "Zipf Frequency",
                "SE, All", "SE, Sentence(N=1)",
                "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
                "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
                "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
            )
        )
    )
```

```{r}
save_fig <- TRUE

sentences_a_en <- "English: He turned around and saw that, in the place of the **dragon**, a man was standing, bowing deeply to him with great<br>ceremony. It was a man of strange appearance, upon whose read hair a crown had been placed in the shape of a **dragon**."
sentences_b_en <- "English: People began to domesticate animals and plants for food, and cities began to form. **Nomadism** generally exists in symbiosis with such<br>settled cultures, exchanging animal products such as meat, hides, wool, and cheese for artisanal goods that are not produced by the **nomadic** herders."

which(levels(factor(df$word)) == "draak,")

p1 <- df_long |>
    filter(sentences_id == "A") |>
    ggplot(aes(x = number_word, y = implementation, fill = value)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey95",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    scale_x_continuous(
        breaks = df$number_word,
        labels = df$word,
    ) +
    labs(
        x = "", y = "", fill = "",
        title = "A",
        caption = sentences_a_en
    ) +
    theme_classic() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.line = element_blank(),
        axis.ticks.y = element_blank(),
        plot.caption = element_markdown(hjust = 0.5),
        plot.caption.position = "plot"
    )

p2 <- df_long |>
    filter(sentences_id == "B") |>
    ggplot(aes(x = number_word, y = implementation, fill = value)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey95",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    scale_x_continuous(
        breaks = df$number_word,
        labels = df$word,
    ) +
    labs(
        x = "", y = "", fill = "",
        title = "B",
        caption = sentences_b_en
    ) +
    theme_classic() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.line = element_blank(),
        axis.ticks.y = element_blank(),
        plot.caption = element_markdown(hjust = 0.5),
        plot.caption.position = "plot"
    )

if (save_fig) {
    p1 / p2 + plot_layout(guides = "collect")
    ggsave(
        file.path(
            "figs",
            paste0("example_sentences.png")
        ),
        height = 6.5, width = 9
    )
} else {
    (p1 + theme(aspect.ratio = .5)) / (p2 + theme(aspect.ratio = .5))
}
```