# Regression coefficients

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(latex2exp)
library(brms)

setwd("experiment2")

source(file.path("..", "src", "model_diagnostics.r"))

models_path <- file.path("analysis", "brms_models")
```

```{r}
dataset <- "derco"

model_names <- list.files(models_path,
    full.names = FALSE,
    pattern = paste0(dataset, "_.*\\.rds$")
)
model_name <- model_names[1]

print(model_name)
m <- readRDS(file.path(models_path, model_name))
summary(m)
```

```{r}
plot(m)
plot(m, variable = "^b_", regex = TRUE)
plot(m, variable = "^sd", regex = TRUE)
```

```{r}
mcmc_plot(m, variable = "^b_[^Intercept]", regex = TRUE) +
    labs(title = model_name) +
    theme(aspect.ratio = .6)
```

## Summarize diagnostics across all models
```{r}
diagnostics_df <- data.frame()

for (dataset in c("tanner", "ucl", "derco")) {
    print(dataset)
    model_names <- list.files(models_path,
        full.names = FALSE,
        pattern = paste0(dataset, "_lp_.*\\.rds$")
    )
    for (model in model_names) {
        print(model)
        fit <- readRDS(
            file.path(models_path, model)
        )
        if (number_divergent_transitions(fit) > 0) {
            print(paste(
                "Divergent transistions! Number:",
                number_divergent_transitions(fit)
            ))
        }
        diag <- diagnostics_rhat_ess(fit) |>
            mutate("dataset" = dataset, "model" = model)

        diagnostics_df <- rbind(diagnostics_df, diag)
    }
}
```

```{r}
diagnostics_df |>
    # group_by(dataset) |>
    # filter(!str_detect(model, "bsemprior")) |>
    summarize(
        "max_rhat" = max(max_rhat),
        "min_ess_bulk" = min(min_ess_bulk),
        "min_ess_tail" = min(min_ess_tail),
        "avg_ess" = mean(avg_ess)
    )

diagnostics_df |>
    # filter(min(min_ess_bulk) == min_ess_bulk) |>
    # filter(min(min_ess_tail) == min_ess_tail) |>
    filter(max(max_rhat) == max_rhat) |>
    select(model)

diagnostics_df |>
    filter(max_rhat >= 1.035) |>
    select(model, max_rhat)
```

## Plot effect of all models
```{r}
get_modelname <- function(text) {
    text <- str_remove(text, "CWE_")
    text <- str_remove(text, "WE_")
    text <- str_remove(text, "SE_")
    text <- str_remove(text, "sentences1_")
    return(text)
}

get_fixef_models <- function(
  datasets,
  include_lp = FALSE,
  only_target = FALSE
) {
    for (dataset in datasets) {
        if (include_lp) {
            prefix <- paste0(dataset, "_lp")
        } else {
            prefix <- dataset
        }

        model_names <- list.files(models_path,
            full.names = FALSE,
            pattern = paste0(prefix, "_.*\\.rds$")
        )

        for (model_name in model_names) {
            if (!include_lp & str_detect(model_name, "lp")) {
                next
            }

            print(model_name)
            m <- readRDS(file.path(models_path, model_name))
            if (number_divergent_transitions(m) > 0) {
                print("Divergent transitions - skips this model")
                next
            }

            implementation <- str_remove(model_name, paste0(prefix, "_"))
            implementation <- str_remove(implementation, ".rds")

            fe_df <- fixef(m) |>
                as.data.frame()
            fe_df$coefficient <- rownames(fe_df)
            fe_df <- fe_df |>
                mutate(
                    "implementation" = implementation,
                    "dataset" = dataset,
                    "model" = get_modelname(implementation),
                    "context" = case_when(
                        str_detect(implementation, "sentences1") ~ "Sentence(N=1)",
                        dataset == "derco" ~ "Sentence(N=10)",
                        .default = "All"
                    )
                )

            if (exists("fixef_df_")) {
                fixef_df_ <- rbind(fixef_df_, fe_df)
            } else {
                fixef_df_ <- fe_df
            }
        }
    }
    return(fixef_df_)
}
```

```{r}
rm(fixef_df)

fixef_df <- get_fixef_models(c("tanner", "ucl", "derco"), include_lp = TRUE)
```

### coefficient for semantic association
```{r}
fixef_df |>
    filter(model != "Gameselo_STS-multilingual-mpnet-base-v2") |>
    filter(context != "Sentence(N=1)") |>
    filter(coefficient == "s_sem") |>
    mutate(model_type = case_when(
        str_detect(implementation, "SE") ~ "SE",
        str_detect(implementation, "CWE") ~ "CWE",
        str_detect(implementation, "WE") ~ "WE"
    )) |>
    mutate(
        dataset = case_when(
            dataset == "tanner" ~ "Tanner (2019)",
            dataset == "ucl" ~ "UCL",
            dataset == "derco" ~ "DERCo"
        ),
        implementation = paste(model_type, model, sep = ":")
    ) |>
    filter(model_type %in% c("SE", "WE", "CWE")) |>
    mutate(
        model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
    ) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(
        values = c(
            "firebrick",
            "steelblue1",
            "steelblue4"
        )
    ) +
    facet_wrap(. ~ dataset, ncol = 1, scale = "free_x") +
    labs(
        x = TeX("$\\beta_2$"), y = "",
        color = "Embeddings"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(file.path("figs", "regression_coefficients_sem.png"), height = 7, width = 7)
```

```{r}
for (d in c("tanner", "ucl", "derco")) {
    fixef_df |>
        filter(model != "Gameselo_STS-multilingual-mpnet-base-v2") |>
        filter(context != "Sentence(N=1)") |>
        filter(dataset == d) |>
        filter(coefficient == "s_sem") |>
        mutate(model_type = case_when(
            str_detect(implementation, "SE") ~ "SE",
            str_detect(implementation, "CWE") ~ "CWE",
            str_detect(implementation, "WE") ~ "WE"
        )) |>
        filter(model_type %in% c("SE", "WE", "CWE")) |>
        mutate(
            model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
        ) |>
        ggplot(aes(y = implementation, color = model_type)) +
        geom_point(aes(x = Estimate)) +
        geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
        geom_vline(aes(xintercept = 0), linetype = "dashed") +
        scale_color_manual(
            values = c(
                "firebrick",
                "steelblue1",
                "steelblue4"
            )
        ) +
        labs(
            x = TeX("$\\beta_2$"), y = "",
            color = "Embeddings"
        ) +
        theme_minimal() +
        theme(legend.position = "bottom")

    ggsave(
        file.path("figs", paste0("regression_coefficients_", d, ".png")),
        height = 3, width = 7
    )
}
```

```{r}
fixef_df |>
    filter(model != "Gameselo_STS-multilingual-mpnet-base-v2") |>
    filter(context == "Sentence(N=1)") |>
    filter(dataset == "derco") |>
    filter(coefficient == "s_sem") |>
    mutate(model_type = case_when(
        str_detect(implementation, "SE") ~ "SE",
        str_detect(implementation, "CWE") ~ "CWE",
        str_detect(implementation, "WE") ~ "WE"
    )) |>
    mutate(
        dataset = case_when(
            dataset == "tanner" ~ "Tanner (2019)",
            dataset == "derco" ~ "DERCo"
        )
    ) |>
    filter(model_type %in% c("SE", "WE", "CWE")) |>
    mutate(
        model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
    ) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(
        values = c(
            "firebrick",
            "steelblue1",
            "steelblue4"
        )
    ) +
    labs(
        x = TeX("$\\beta_2$"), y = "",
        color = "Embeddings",
        caption = "Sentence(N=1)"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(
    file.path("figs", "regression_coefficients_derco_sentences1.png"),
    height = 3, width = 7
)
```

### coefficient for lp
```{r}
fixef_df |>
    filter(model != "Gameselo_STS-multilingual-mpnet-base-v2") |>
    filter(context != "Sentence(N=1)") |>
    filter(coefficient == "s_lp") |>
    mutate(model_type = case_when(
        str_detect(implementation, "SE") ~ "SE",
        str_detect(implementation, "CWE") ~ "CWE",
        str_detect(implementation, "WE") ~ "WE"
    )) |>
    mutate(
        dataset = case_when(
            dataset == "tanner" ~ "Tanner (2019)",
            dataset == "ucl" ~ "UCL",
            dataset == "derco" ~ "DERCo"
        )
    ) |>
    filter(model_type %in% c("SE", "WE", "CWE")) |>
    mutate(
        model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
    ) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(
        values = c(
            "firebrick",
            "steelblue1",
            "steelblue4"
        )
    ) +
    facet_wrap(. ~ dataset, ncol = 1, scale = "free_x") +
    labs(
        x = TeX("$\\beta_1$"), y = "",
        color = "Embeddings"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(file.path("figs", "regression_coefficients_lp.png"), height = 7, width = 7)
```

### coefficient only including target word from Tanner 
```{r}
rm(fixef_target_df)

fixef_target_df <- get_fixef_models(c("tanner_target"))
```

```{r}
fixef_target_df |>
    filter(model != "Gameselo_STS-multilingual-mpnet-base-v2") |>
    filter(context == "All") |>
    filter(coefficient == "s_sem") |>
    mutate(model_type = case_when(
        str_detect(implementation, "SE") ~ "SE",
        str_detect(implementation, "CWE") ~ "CWE",
        str_detect(implementation, "WE") ~ "WE"
    )) |>
    filter(model_type %in% c("SE", "WE", "CWE")) |>
    mutate(
        model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
    ) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(
        values = c(
            "firebrick",
            "steelblue1",
            "steelblue4"
        )
    ) +
    labs(
        x = TeX("$\\beta_2$"), y = "",
        color = "Embeddings"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(file.path("figs", "tanner_target_regression_coefficients_sem.png"), height = 3, width = 7)
```

```{r}
fixef_target_df |>
    filter(context == "All") |>
    filter(coefficient == "s_lp") |>
    mutate(model_type = case_when(
        str_detect(implementation, "SE") ~ "SE",
        str_detect(implementation, "CWE") ~ "CWE",
        str_detect(implementation, "WE") ~ "WE"
    )) |>
    filter(model_type %in% c("SE", "WE", "CWE")) |>
    mutate(
        model_type = factor(model_type, levels = c("SE", "WE", "CWE")),
    ) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(
        values = c(
            "firebrick",
            "steelblue1",
            "steelblue4"
        )
    ) +
    labs(
        x = TeX("$\\beta_1$"), y = "",
        color = "Embeddings"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(file.path("figs", "tanner_target_regression_coefficients_lp.png"), height = 3, width = 7)
```