# Correlation between human association and lm association

```{r}
library(tidytable)
library(readxl)
library(stringr)
library(ggplot2)
library(reshape2)

setwd("experiment1")

exclude_models <- c(
    "Gameselo/STS-multilingual-mpnet-base-v2",
    "jinaai/jina-embeddings-v2-base-de",
    "sentence-transformers/stsb-xlm-r-multilingual",
    "aari1995/German_Semantic_V3b"
)

remove_organization <- function(text) {
    text <- str_remove(text, "Qwen/")
    text <- str_remove(text, "BAAI/")
    text <- str_remove(text, "intfloat/")
    text <- str_remove(text, "Gameselo/")
    text <- str_remove(text, "jinaai/")
    text <- str_remove(text, "aari1995/")
    text <- str_remove(text, "sentence-transformers/")
    return(text)
}
```

## Delogu et al. (2019)
```{r}
assoc_df <- read.csv(file.path("data", "Delogu", "dbc_data.csv")) |>
    select(ItemNum, Condition, Assoc, Plaus) |>
    distinct()

lp_df <- read.csv(file.path("results", "delogu_log_probability.csv")) |>
    select(-X)

delogu_df <- read.csv(file.path("results", "delogu_semantic_association.csv")) |>
    left_join(assoc_df) |>
    left_join(lp_df) |>
    filter(!model %in% exclude_models) |>
    mutate("cond" = factor(Condition,
        levels = c("control", "script-related", "script-unrelated")
    )) |>
    mutate(
        full_implementation = paste(implementation, remove_organization(model), sep = ", ")
    )
```

```{r}
cor_matrix <- delogu_df |>
    select(semantic_association, Assoc, Plaus, lp_benjamin_gerpt2, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), "Assoc", , "lp_benjamin_gerpt2") |>
    rename(
        "Human rated association" = "Assoc",
        "Log-probability, GerPT2" = "lp_benjamin_gerpt2"
    ) |>
    cor(method = "pearson", use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Pearson's r") +
    theme(aspect.ratio = 1)

ggsave(file.path("figs", "delogu_correlations.png"), width = 7, height = 5)
```

## Aurnhammer et al. (2021)
```{r}
lp_df <- read.csv(file.path("results", "aurnhammer_log_probability.csv")) |>
    select(-X)

aurnhammer_df <- read.csv(file.path("results", "aurnhammer_semantic_association.csv")) |>
    left_join(lp_df) |>
    mutate(cond = case_when(
        Condition == "A" ~ "A+E+",
        Condition == "B" ~ "A-E+",
        Condition == "C" ~ "A+E-",
        Condition == "D" ~ "A-E-"
    )) |>
    mutate("cond" = factor(cond,
        levels = c("A+E+", "A-E+", "A+E-", "A-E-")
    )) |>
    mutate(full_implementation = paste(implementation, model, sep = ", ")) |>
    filter(!model %in% exclude_models)
```

```{r}
cor_matrix <- aurnhammer_df |>
    select(semantic_association, starts_with("Association"), lp_benjamin_gerpt2, full_implementation) |>
    pivot_wider(
        names_from = full_implementation,
        values_from = semantic_association,
        names_prefix = "semantic_association_"
    ) |>
    select(starts_with("semantic_association"), starts_with("Association"), "lp_benjamin_gerpt2") |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

matrix_names <- colnames(cor_matrix)
matrix_names <- colnames(cor_matrix)
name_order <- order(
    case_when(
        str_starts(matrix_names, "WE") ~ 1L,
        str_starts(matrix_names, "CWE") ~ 2L,
        str_starts(matrix_names, "SE") ~ 3L,
        TRUE ~ 4L
    ),
    matrix_names
)

cor_matrix <- cor_matrix[name_order, name_order]
melted <- melt(cor_matrix)

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```