# Model comparison with the Bayes factor

```{r}
library(tidytable)
library(stringr)
library(brms)
library(polspline)
library(bridgesampling)
library(ggplot2)
library(latex2exp)

setwd("experiment1")

options(mc.cores = parallel::detectCores())

models_path <- file.path("analysis", "brms_models")

exclude_models <- c(
  "STS-multilingual-mpnet-base-v2",
  "jina-embeddings-v2-base-de",
  "German_Semantic_V3b",
  "stsb-xlm-r-multilingual"
)
```

## helper functions
```{r}
# returns the sd for the prior of beta_2 (b_s_sem)
get_sem_prior_sd <- function(fit, beta = "s_sem") {
  priors_b <- fit$prior[fit$prior$class == "b", c("prior", "coef")]
  prior_b_sem <- priors_b[priors_b$coef == beta, "prior"]

  if (prior_b_sem == "") {
    # then all priors of beta is the same
    prior_b_sem <- priors_b[priors_b$coef == "", "prior"]
  }

  prior_b_sem_sd <- str_extract(prior_b_sem, "(?<=, )[0-9.]+")
  return(as.numeric(prior_b_sem_sd))
}

# get name of implementation from model name
get_implementation <- function(model_name) {
  case_when(
    str_detect(model_name, "_SE_") ~ "SE",
    str_detect(model_name, "_CWE_") ~ "CWE",
    str_detect(model_name, "_WE_") ~ "WE",
    str_detect(model_name, "_assoc") ~ "Human rating"
  )
}

# get embedding model name from implementation
get_modelname <- function(text) {
  text <- str_extract(text, "(?<=lp_).*?(?=\\.rds|_bsemprior)")

  # remove implementation
  text <- str_remove(text, "CWE_")
  text <- str_remove(text, "WE_")
  text <- str_remove(text, "SE_")
  text <- str_remove(text, "sentences1_")
  text <- str_remove(text, "all_")
  # remove organization
  text <- str_remove(text, "Qwen_")
  text <- str_remove(text, "BAAI_")
  text <- str_remove(text, "intfloat_")
  text <- str_remove(text, "Gameselo_")
  text <- str_remove(text, "jinaai_")
  text <- str_remove(text, "aari1995_")
  text <- str_remove(text, "sentence-transformers_")
  return(text)
}
```

## calculate Savage-Dickey ratio of s_sem beta estimate
```{r}
rm(sd_df)

sem_model_names <- list.files(
  models_path,
  full.names = FALSE,
  pattern = "delogu_(lp|assoc_lp).*\\.rds$"
)

for (reg_model_name in sem_model_names) {
  if (str_detect(reg_model_name, "samples")) {
    next # skip models with more samples (for bridgesampling below)
  }
  print(reg_model_name)
  sem_m <- readRDS(file.path(models_path, reg_model_name))

  if (str_detect(reg_model_name, "_assoc")) {
    prior_sd <- get_sem_prior_sd(sem_m, beta = "s_assoc")
    posterior_sem <- sem_m |>
      as_draws_df() |>
      pull(b_s_assoc)
  } else {
    prior_sd <- get_sem_prior_sd(sem_m)
    posterior_sem <- sem_m |>
      as_draws_df() |>
      pull(b_s_sem)
  }

  # savage-dickey ratio
  fit_posterior <- logspline(posterior_sem)
  posterior <- dlogspline(0, fit_posterior) # Height of the posterior at 0
  prior <- dnorm(0, mean = 0, sd = prior_sd) # Height of the prior at 0
  BF01 <- posterior / prior


  tmp_df <- data.frame(
    "posterior" = posterior,
    "prior" = prior,
    "BF01" = BF01,
    "prior_sd" = prior_sd,
    "reg_model_name" = reg_model_name,
    "implementation" = get_implementation(reg_model_name),
    "embedding_model" = get_modelname(reg_model_name)
  )

  if (exists("sd_df")) {
    sd_df <- rbind(tmp_df, sd_df)
  } else {
    sd_df <- tmp_df
  }
}
```

### plot
```{r}
# Custom breaks
custom_breaks <- c(100, 30, 10, 3, 1, 1 / 3, 1 / 10, 1 / 30, 1 / 100, 1 / 300)
custom_labels <- c("100", "30", "10", "3", "1", "1/3", "1/10", "1/30", "1/100", "1/300")

sd_df |>
  filter(!embedding_model %in% exclude_models) |>
  mutate("implementation" = factor(implementation, levels = c("Human rating", "WE", "CWE", "SE"))) |>
  mutate("full_imp" = ifelse(
    implementation == "Human rating",
    "Human-rated association",
    paste(implementation, embedding_model, sep = ", ")
  )) |>
  arrange(implementation, embedding_model) |>
  mutate(
    full_imp = factor(
      full_imp,
      levels = rev(unique(full_imp))
    )
  ) |>
  ggplot(aes(
    y = full_imp,
    color = implementation,
    shape = as.factor(prior_sd)
  )) +
  geom_line(aes(x = BF01, group = full_imp), linetype = "dashed", color = "grey") +
  geom_point(aes(x = BF01), size = 2) +
  geom_vline(aes(xintercept = 1), linetype = "dotted") +
  scale_x_log10(
    breaks = custom_breaks,
    labels = custom_labels,
    limits = c(1 / 300, 50)
  ) +
  theme_minimal() +
  scale_shape_manual(values = c(17, 4, 16)) +
  scale_color_manual(
    values = c(
      "darkorange",
      "steelblue1",
      "steelblue4",
      "firebrick"
    )
  ) +
  labs(x = TeX("$\\BF_{01}$"), y = "", color = "", shape = "SD of prior") +
  theme(legend.position = "bottom", legend.box = "vertical")

ggsave(file.path("figs", "Savage-Dickey.png"), width = 7, height = 3.5)
```

## Bridge sampling: human association vs embedding-based association
```{r}
embedding_implementation <- "SE_aari1995_German_Semantic_STS_V2"

emb_model_names <- list.files(
  models_path,
  full.names = FALSE,
  pattern = paste0("delogu_lp_", embedding_implementation, "_samples20000.*\\.rds$")
)

for (emb_model_name in emb_model_names) {
  prior_suffix <- str_remove(
    emb_model_name,
    paste0("delogu_lp_", embedding_implementation, "_samples20000")
  )
  human_model_name <- paste0("delogu_assoc_lp_samples20000", prior_suffix)

  fit_human <- readRDS(file.path(models_path, human_model_name))
  fit_embed <- readRDS(file.path(models_path, emb_model_name))

  margLogLik_human <- bridge_sampler(fit_human, silent = TRUE)
  margLogLik_embed <- bridge_sampler(fit_embed, silent = TRUE)

  BF <- bayes_factor(margLogLik_human, margLogLik_embed)

  prior <- str_remove(prior_suffix, ".rds")
  prior <- str_remove(prior, "_bsemprior")
  if (prior == "") {
    print("SD of Prior = 10")
  } else {
    print(paste("Sd of prior =", prior))
  }
  print(paste("x1 = human, x2 =", embedding_implementation))
  print(BF)
}
```
[1] "SD of Prior = 10"
[1] "x1 = human, x2 = SE_aari1995_German_Semantic_STS_V2"
Estimated Bayes factor in favor of x1 over x2: 66.52447
[1] "Sd of prior = 1"
[1] "x1 = human, x2 = SE_aari1995_German_Semantic_STS_V2"
Estimated Bayes factor in favor of x1 over x2: 58.75929
[1] "Sd of prior = 2"
[1] "x1 = human, x2 = SE_aari1995_German_Semantic_STS_V2"
Estimated Bayes factor in favor of x1 over x2: 61.98005



