# Model comparison using PSIS-LOO

```{r}
library(tidytable)
library(stringr)
library(brms)
library(loo)
library(ggplot2)

setwd("extra_experiments")

source(file.path("..", "src", "model_diagnostics.r"))

exp2_models_path <- file.path("..", "experiment2", "analysis", "brms_models")
extra_experiments_models_path <- file.path("analysis", "brms_models")
```

## joint model
### Read models
```{r}
# read joint model
joint_prefix <- "derco_both_"

joint_model_name <- list.files(extra_experiments_models_path,
    full.names = FALSE,
    pattern = paste0(joint_prefix, ".*\\.rds$")
)[1]

print(joint_model_name)
joint_fit <- readRDS(file.path(extra_experiments_models_path, joint_model_name))

# read individual SE and WE models
individual_model_names <- str_remove(joint_model_name, joint_prefix)
individual_model_names <- str_remove(individual_model_names, ".rds")

se_model_name <- str_extract(individual_model_names, "^SE_.+?(?=_WE_)")
we_model_name <- str_extract(individual_model_names, "WE_.+$")

individual_prefix <- "derco_lp_"

print(se_model_name)
se_fit <- readRDS(
    file.path(
        exp2_models_path,
        paste0(individual_prefix, se_model_name, ".rds")
    )
)

print(we_model_name)
we_fit <- readRDS(
    file.path(
        exp2_models_path,
        paste0(individual_prefix, we_model_name, ".rds")
    )
)
```

### Summarize diagnostics across models
```{r}
fit <- joint_fit

if (number_divergent_transitions(fit) > 0) {
    print(paste(
        "Divergent transistions! Number:",
        number_divergent_transitions(fit)
    ))
}
diagnostics_rhat_ess(fit)
```

### model comparison
```{r}
loo_joint <- loo(joint_fit)
loo_se <- loo(se_fit)
loo_we <- loo(we_fit)
```

```{r}
# psis diagnostics
loo_joint
plot(loo_joint)

loo_se
plot(loo_se)

loo_we
plot(loo_we)
```

```{r}
comparison <- loo_compare(loo_joint, loo_se, loo_we)
print(comparison, digits = 2)
```
          elpd_diff se_diff
joint_fit  0.00      0.00  
se_fit    -4.65      4.69  
we_fit    -5.24      4.27 

## word position models
### read models
```{r}
# read models
dataset <- "ucl"

model1_name <- "SE_Qwen_Qwen3-Embedding-8B"
model2_name <- "WE_enwiki_20180420_300d"

print(model1_name)
model1_fit <- readRDS(
    file.path(
        extra_experiments_models_path,
        paste0(dataset, "_wordn_", model1_name, ".rds")
    )
)

print(model2_name)
model2_fit <- readRDS(
    file.path(
        extra_experiments_models_path,
        paste0(dataset, "_wordn_", model2_name, ".rds")
    )
)
```

### model comparison
```{r}
loo1 <- loo(model1_fit)
loo2 <- loo(model2_fit)
```

```{r}
# psis diagnostics
loo1
plot(loo1)

loo2
plot(loo2)
```

```{r}
comparison <- loo_compare(loo1, loo2)
print(comparison, digits = 2)
```