# Predictions of regression models from experiment 3

```{r}
library(tidytable)
library(dplyr)
library(brms)
library(stringr)
library(ggplot2)
library(ltc)

setwd("extra_experiments")

models_path <- file.path("..", "experiment3", "analysis", "brms_models")

# content words pos tags
content_pos <- c("NOUN", "VERB", "ADJ", "ADV")
```

```{r}
# function for cleaning word
clean_word <- function(word) {
    word |>
        tolower() |>
        gsub("[[:punct:]]", "", x = _)
}

# function for getting the implementation_id from the model filename
get_implementation_id <- function(filename, dataset) {
    imp_id <- str_remove(filename, paste0(dataset, "_"))
    imp_id <- str_remove(imp_id, "lp_")
    imp_id <- str_remove(imp_id, ".rds")
    return(imp_id)
}
```

## read data
```{r}
derco_sem <- read.csv(
    file.path("..", "experiment3", "results", "derco_semantic_association.csv")
) |>
    select(-X) |>
    tidytable::mutate(
        implementation_id = paste(implementation, model, sep = "_")
    ) |>
    tidytable::mutate(implementation_id = str_replace(implementation_id, "/", "_"))
derco_df <- read.csv(
    file.path("..", "experiment3", "data", "DERCo", "mean_amplitude.csv")
) |>
    tidytable::left_join(derco_sem) |>
    tidytable::filter(pos %in% content_pos) |>
    tidytable::mutate(word = clean_word(target)) |>
    # only use complete cases across implementations of sem
    tidytable::group_by(article_n, word_n) |>
    tidytable::filter(all(!is.na(semantic_association))) |>
    tidytable::ungroup() |>
    arrange(subject, article_n, word_n)
```

## load model
```{r}
dataset <- "derco"

model_names <- list.files(models_path,
    full.names = FALSE,
    pattern = paste0(dataset, "_lp*_.*\\.rds$")
)
model_name <- model_names[13]

print(model_name)
fit <- readRDS(file.path(models_path, model_name))
summary(fit)
```

## residuals
```{r}
# data for one model
vars <- c(
    "n400",
    "s_sem",
    "s_lp",
    "subject",
    "article_n",
    "word"
)
data <- derco_df |>
    filter(implementation_id == get_implementation_id(model_name, dataset)) |>
    tidytable::mutate(
        "s_sem" = scale(semantic_association)
    ) |>
    filter(if_all(all_of(vars), ~ !is.na(.)))
```

```{r}
# preds <- fitted(fit)
preds <- predict(fit)
data$pred <- preds[, "Estimate"]
data$pred_Q2.5 <- preds[, "Q2.5"]
data$pred_Q97.5 <- preds[, "Q97.5"]
data$resid <- data$n400 - data$pred
```

```{r}
var_name <- "s_sem"

tmp_data <- data |>
    rename("var" = var_name)

tmp_data |>
    ggplot(aes(x = var)) +
    geom_errorbar(aes(ymin = pred_Q2.5, ymax = pred_Q97.5), color = "steelblue") +
    geom_point(aes(y = n400)) +
    geom_point(aes(y = pred), color = "steelblue") +
    theme_minimal() +
    labs(
        x = var_name,
        title = model_name,
        caption = "Blue is predictions, black is observed N400"
    ) +
    theme(aspect.ratio = 0.7)

tmp_data |>
    mutate(bin = ntile(var, 10)) |>
    group_by(bin) |>
    summarize(
        max_var = max(var),
        rmse = sqrt(mean((resid)^2)),
        mae = mean(abs(resid)),
        bias = mean(resid)
    )
```

```{r}
data |>
    ggplot(aes(x = s_lp, y = s_sem)) +
    geom_point(aes(color = resid)) +
    theme_minimal() +
    scale_color_gradient2(low = "blue3", high = "red2", mid = "thistle1") +
    labs(
        title = model_name,
        color = "Residuals"
    ) +
    theme(aspect.ratio = 0.7)
```
