# Correlations between predictors (lp and sem)

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(reshape2)

source(file.path("src", "rename_implementations.r"))
```

## Load data
```{r}
sem_df <- read.csv(
    file.path("results", "tint_semantic_association.csv")
)

tint_df <- read.csv(file.path("data", "tint_stim.csv")) |>
    select(-X) |>
    mutate(content_word = ifelse(
        pos %in% c("NOUN", "VERB", "ADJ", "ADV"),
        TRUE, FALSE
    )) |>
    left_join(sem_df)
```

## Correlations
all words
```{r}
cor_matrix <- tint_df |>
    select(lp, zipf_freq, starts_with("semantic_association")) |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

# rename implementations
colnames(cor_matrix) <- rename_implementations(colnames(cor_matrix))
rownames(cor_matrix) <- rename_implementations(rownames(cor_matrix))

# rename freq and lp
colnames(cor_matrix) <- case_when(
    colnames(cor_matrix) == "zipf_freq" ~ "Zipf Frequency",
    colnames(cor_matrix) == "lp" ~ "Log Probability",
    .default = colnames(cor_matrix)
)
rownames(cor_matrix) <- case_when(
    rownames(cor_matrix) == "zipf_freq" ~ "Zipf Frequency",
    rownames(cor_matrix) == "lp" ~ "Log Probability",
    .default = rownames(cor_matrix)
)

cor_matrix
```

```{r}
melted <- melt(cor_matrix) |>
    mutate(
        Var1 = factor(Var1, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        )),
        Var2 = factor(Var2, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        ))
    )

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

only content words
```{r}
cor_matrix <- tint_df |>
    filter(content_word) |>
    select(lp, zipf_freq, starts_with("semantic_association")) |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

# rename implementations
colnames(cor_matrix) <- rename_implementations(colnames(cor_matrix))
rownames(cor_matrix) <- rename_implementations(rownames(cor_matrix))

# rename freq and lp
colnames(cor_matrix) <- case_when(
    colnames(cor_matrix) == "zipf_freq" ~ "Zipf Frequency",
    colnames(cor_matrix) == "lp" ~ "Log Probability",
    .default = colnames(cor_matrix)
)
rownames(cor_matrix) <- case_when(
    rownames(cor_matrix) == "zipf_freq" ~ "Zipf Frequency",
    rownames(cor_matrix) == "lp" ~ "Log Probability",
    .default = rownames(cor_matrix)
)

cor_matrix
```

```{r}
melted <- melt(cor_matrix) |>
    mutate(
        Var1 = factor(Var1, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        )),
        Var2 = factor(Var2, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        ))
    )

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom"
    ) +
    labs(x = "", y = "", fill = "Correlation")

ggsave(file.path("figs", "correlations_CW.png"), height = 5.5, width = 5)
```

specific pos
```{r}
tint_df |>
    pull(pos) |>
    unique()

cor_matrix <- tint_df |>
    filter(pos == "NOUN") |>
    select(lp, zipf_freq, starts_with("semantic_association")) |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

cor_matrix
```

```{r}
melted <- melt(cor_matrix) |>
    mutate(
        Var1 = factor(Var1, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        )),
        Var2 = factor(Var2, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        ))
    )

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```

specific documents
```{r}
cor_matrix <- tint_df |>
    filter(document_id == 1) |>
    filter(content_word) |>
    select(lp, zipf_freq, starts_with("semantic_association")) |>
    cor(use = "pairwise.complete.obs")

# Remove prefix
prefix <- "^semantic_association_"
colnames(cor_matrix) <- str_remove(colnames(cor_matrix), prefix)
rownames(cor_matrix) <- str_remove(rownames(cor_matrix), prefix)

cor_matrix
```

```{r}
melted <- melt(cor_matrix) |>
    mutate(
        Var1 = factor(Var1, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        )),
        Var2 = factor(Var2, levels = c(
            "Log Probability", "Zipf Frequency",
            "SE, All", "SE, Sentence(N=1)",
            "WE, All", "WE, Sentence(N=1)", "WE, Weighted",
            "CWE, All", "CWE, Sentence(N=1)", "CWE, Weighted",
            "CWE, Windowed(N=1)", "CWE, Windowed(N=2)"
        ))
    )

ggplot(melted, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    geom_text(aes(label = round(value, 2)), color = "black", size = 3) +
    scale_fill_gradient2(
        low = "blue", high = "red", mid = "white",
        midpoint = 0, limit = c(-1, 1)
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "", y = "", fill = "Correlation") +
    theme(aspect.ratio = 1)
```