# temporary file for checking that the regression models are correct

```{r}
library(tidytable)
library(stringr)
library(ggplot2)
library(brms)
```

```{r}
dep_var <- "p600"
model_names <- list.files(file.path("analysis", "brms_models"),
    full.names = FALSE,
    pattern = paste0(dep_var, "_.*\\.rds$")
)
model_name <- model_names[5]

print(model_name)
m <- readRDS(file.path("analysis", "brms_models", model_name))
summary(m)
```

```{r}
plot(m)
plot(m, variable = "^b_", regex = TRUE)
```

```{r}
mcmc_plot(m, variable = "^b_[^Intercept]", regex = TRUE) +
    labs(title = model_name) +
    theme(aspect.ratio = .6)
```

## Plot effect of all models
```{r}
rm(fixef_df)
dep_var <- "n400"
model_formula <- "only_semantic_association"

model_names <- list.files(file.path("analysis", "brms_models"),
    full.names = FALSE,
    pattern = paste0(dep_var, "_", model_formula, "_.*\\.rds$")
)

for (model_name in model_names) {
    print(model_name)
    m <- readRDS(file.path("analysis", "brms_models", model_name))

    if (str_detect(model_name, "SentenceEmbeddingModelSingleWord")) {
        model_name <- str_replace(
            model_name,
            "SentenceEmbeddingModelSingleWord",
            "SentenceEmbeddingSingleWord"
        )
    }

    fe_df <- fixef(m) |>
        as.data.frame()
    fe_df$coefficient <- rownames(fe_df)
    fe_df <- fe_df |>
        filter(coefficient == "s_sem") |>
        mutate(
            "implementation" = str_replace(
                model_name,
                paste0(dep_var, "_", model_formula, "_"), ""
            )
        ) |>
        mutate(
            "implementation" = str_replace(
                implementation, ".rds", ""
            )
        )

    if (exists("fixef_df")) {
        fixef_df <- rbind(fixef_df, fe_df)
    } else {
        fixef_df <- fe_df
    }
}
```

```{r}
if (model_formula == "semantic_association") {
    predictors <- "lp + sem"
} else if (model_formula == "only_semantic_association") {
    predictors <- "sem"
} else if (model_formula == "baseline") {
    predictors <- "lp"
}

fixef_df |>
    mutate(model_type = case_when(
        str_detect(implementation, "WordEmbedding300") ~ "WordEmbedding300",
        str_detect(implementation, "SentenceEmbeddingSingleWord") ~ "SentenceEmbeddingModelSingleWord",
        str_detect(implementation, "SentenceEmbedding") ~ "SentenceEmbedding",
        str_detect(implementation, "WordEmbedding") ~ "WordEmbedding"
    )) |>
    ggplot(aes(y = implementation, color = model_type)) +
    geom_point(aes(x = Estimate)) +
    geom_linerange(aes(xmin = Q2.5, xmax = Q97.5)) +
    geom_vline(aes(xintercept = 0), linetype = "dashed") +
    scale_color_manual(values = c("steelblue", "slateblue", "firebrick", "violetred")) +
    labs(
        x = "Estimate Semantic Assocation", y = "",
        title = paste(toupper(dep_var), "~", predictors)
    ) +
    theme_minimal() +
    theme(legend.position = "bottom")

ggsave(
    file.path("figs", paste0("coefficients_", dep_var, "_", model_formula, ".png")),
    height = 5, width = 11
)
```