# Exploration of Kuperberg (2003 and 2007)

```{r}
library(tidytable)
library(readxl)
library(ggplot2)
library(pangoling)

setwd("experiment1")
```

## Read data
```{r}
subtlex <- read_excel(file.path("data", "Subtlex-US.xlsx")) |>
    rename(
        "target" = "Word",
        "zipf_freq" = "Zipf-value"
    ) |>
    select(target, zipf_freq)

stim <- read_excel(file.path("data", "Kuperberg", "sentences.xlsx")) |>
    left_join(subtlex) |>
    mutate(wl = nchar(target)) |>
    filter(!is.na(target))
```

## Explore stimuli
```{r}
stim |>
    group_by(scenario) |>
    mutate(
        "n_unique_sentences" = length(unique(sentences))
    ) |>
    filter(n_unique_sentences != 4) |>
    select(sentences)
```

Word length
```{r}
stim |>
    select(wl) |>
    summary()

stim |>
    ggplot() +
    geom_density(aes(x = wl), fill = "aliceblue", alpha = .5) +
    labs(title = "Word length") +
    theme_minimal()
```

Word frequency
```{r}
stim |>
    select(zipf_freq) |>
    summary()

stim |>
    ggplot() +
    geom_density(aes(x = zipf_freq), fill = "aliceblue", alpha = .5) +
    labs(title = "Zipf frequency") +
    theme_minimal()
```

Log-probability
```{r}
# get lp
# causal_preload("gpt2")
causal_preload("EleutherAI/pythia-70m-deduped")

stim <- stim |>
    # mutate("lp_gpt2" = causal_targets_pred(
    #     contexts = context,
    #     targets = target,
    #     model = "gpt2",
    #     batch_size = 10
    # ))
    mutate("lp_pythia" = causal_targets_pred(
        contexts = context,
        targets = target,
        model = "EleutherAI/pythia-70m-deduped",
        batch_size = 10
    ))
```

```{r}
stim |>
    ggplot() +
    geom_density(aes(x = lp_pythia), fill = "aliceblue", alpha = .5) +
    labs(title = "lp") +
    theme_minimal()

stim |>
    mutate(cond = as.factor(cond)) |>
    ggplot() +
    geom_density(aes(x = lp_pythia, fill = cond, group = cond), alpha = .5) +
    labs(title = "lp") +
    theme_minimal()
```

```{r}
stim |>
    group_by(cond) |>
    summarize(
        mean_lp = mean(lp_pythia),
        sd_lp = sd(lp_pythia)
    ) |>
    ggplot(aes(x = cond)) +
    geom_point(aes(y = mean_lp)) +
    geom_errorbar(
        aes(
            ymin = (mean_lp - sd_lp),
            ymax = (mean_lp + sd_lp)
        ),
        width = 0.2
    ) +
    theme_minimal()

ggsave("figs/lp_kuperberg_pythia.png")
```

```{r}
stim |>
    select(context, target, lp_gpt2, lp_pythia, cond) |>
    print(n = 8)
```

```{r}
cor.test(stim$lp, stim$lp_pythia)
```