# Exploration of Delogu (2019)

```{r}
library(tidytable)
library(readxl)
library(ggplot2)

setwd("experiment1")
```

## Read data
```{r}
stim <- read_excel(file.path("data", "delogu_2019_stim.xlsx")) |>
    mutate(wl = nchar(target))

stim_nl <- read.csv(file.path("data", "delogu_2019_stim_nl.csv")) |>
    mutate(wl = nchar(target))
```

## Exploration
```{r}
stim |> head()
stim_nl |> head()
```

Word length
```{r}
stim |>
    select(wl) |>
    summary()

stim |>
    ggplot() +
    geom_density(aes(x = wl), fill = "aliceblue", alpha = .5) +
    labs(title = "Word length") +
    theme_minimal()
```

```{r}
stim_nl |>
    select(wl) |>
    summary()

stim_nl |>
    ggplot() +
    geom_density(aes(x = wl), fill = "aliceblue", alpha = .5) +
    labs(title = "Word length") +
    theme_minimal()
```

## Compare original and Dutch translations
```{r}
md_text <- c()

for (i in 1:90) {
    for (c in c("control", "script-related", "script-unrelated")) {
        sent_nl <- stim_nl |>
            filter(ItemNum == i & Condition == c)
        sent <- stim |>
            filter(ItemNum == i & Condition == c)

        md_text <- c(
            md_text,
            paste0(i, ". ", sent_nl$context, " **", sent_nl$target, "** ", sent_nl$continuation)
        )
        md_text <- c(
            md_text,
            paste0("*", sent$context, " ", sent$target, " ", sent$continuation, "*")
        )
    }
    md_text <- c(md_text, " ")
}

writeLines(md_text, file.path("data", "delogu", "delogu_translated_sentences.md"))
```