# Kuperberg, 2003 and 2007

```{r}
library(tidytable)
library(readxl)
library(ggplot2)
library(pangoling)

setwd("experiment1")
```

## Read data
```{r}
subtlex <- read_excel(file.path("data", "Subtlex-US.xlsx")) |>
    rename(
        "target" = "Word",
        "zipf_freq" = "Zipf-value"
    ) |>
    select(target, zipf_freq)

stim <- read_excel(file.path("data", "Kuperberg", "sentences.xlsx")) |>
    left_join(subtlex) |>
    mutate(wl = nchar(target)) |>
    filter(!is.na(target))

sem_df <- read.csv(file.path("results", "kuperberg_semantic_association.csv"))
```

## Inspect stimuli
Word length
```{r}
stim |>
    select(wl) |>
    summary()

stim |>
    ggplot() +
    geom_density(aes(x = wl), fill = "aliceblue", alpha = .5) +
    labs(title = "Word length") +
    theme_minimal()
```

Word frequency
```{r}
stim |>
    select(zipf_freq) |>
    summary()

stim |>
    ggplot() +
    geom_density(aes(x = zipf_freq), fill = "aliceblue", alpha = .5) +
    labs(title = "Zipf frequency") +
    theme_minimal()
```

Log-probability
```{r}
# get lp
# causal_preload("gpt2")
causal_preload("EleutherAI/pythia-70m-deduped")

stim <- stim |>
    mutate("lp_pythia" = causal_targets_pred(
        contexts = context,
        targets = target,
        model = "EleutherAI/pythia-70m-deduped",
        batch_size = 10
    ))
```

```{r}
stim |>
    ggplot() +
    geom_density(aes(x = lp_pythia), fill = "aliceblue", alpha = .5) +
    labs(title = "lp") +
    theme_minimal()

stim |>
    mutate(cond = as.factor(cond)) |>
    ggplot() +
    geom_density(aes(x = lp_pythia, fill = cond, group = cond), alpha = .5) +
    labs(title = "lp") +
    theme_minimal()
```

```{r}
stim |>
    group_by(cond) |>
    summarize(
        mean_lp = mean(lp_pythia),
        sd_lp = sd(lp_pythia)
    ) |>
    ggplot(aes(x = cond)) +
    geom_point(aes(y = mean_lp)) +
    geom_errorbar(
        aes(
            ymin = (mean_lp - sd_lp),
            ymax = (mean_lp + sd_lp)
        ),
        width = 0.2
    ) +
    theme_minimal()

ggsave("figs/lp_kuperberg_pythia.png")
```

```{r}
stim |>
    select(context, target, lp, lp_pythia, cond) |>
    print(n = 8)
```

```{r}
cor.test(stim$lp, stim$lp_pythia)
```

## semantic association
By condition
```{r}
sem_df |>
    group_by(cond) |>
    summarize(
        "mean" = mean(semantic_association, na.rm = TRUE),
        "sd" = sd(semantic_association, na.rm = TRUE),
        "max" = max(semantic_association, na.rm = TRUE),
        "min" = min(semantic_association, na.rm = TRUE),
        "NAs" = sum(is.na(semantic_association))
    )
```

```{r}
sem_df |>
    mutate("cond" = as.factor(cond)) |>
    group_by(implementation, model, cond) |>
    summarize(
        "mean" = mean(semantic_association, na.rm = TRUE),
        "sd" = sd(semantic_association, na.rm = TRUE)
    ) |>
    ggplot(aes(x = model, color = cond, group = cond)) +
    geom_point(
        aes(y = mean),
        position = position_dodge(width = 0.3),
        size = 2
    ) +
    geom_errorbar(
        aes(ymin = mean - sd, ymax = mean + sd),
        width = 0.15,
        position = position_dodge(width = 0.3)
    ) +
    scale_colour_manual(
        values = c("blue", "firebrick2", "purple", "orange")
    ) +
    labs(x = "") +
    facet_wrap(. ~ implementation, ncol = 2, scales = "free") +
    theme_minimal() +
    theme(
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

```{r}
sem_df |>
    mutate("cond" = as.factor(cond)) |>
    group_by(model, implementation, cond) |>
    summarize(
        "mean" = mean(semantic_association, na.rm = TRUE),
        "sd" = sd(semantic_association, na.rm = TRUE)
    ) |>
    ggplot(aes(x = cond, color = cond, group = cond)) +
    geom_point(
        aes(y = mean),
        position = position_dodge(width = 0.3),
        size = 2
    ) +
    geom_errorbar(
        aes(ymin = mean - sd, ymax = mean + sd),
        width = 0.15,
        position = position_dodge(width = 0.3)
    ) +
    scale_colour_manual(
        values = c("blue", "firebrick2", "purple", "orange")
    ) +
    facet_wrap(implementation ~ model, ncol = 3, scales = "free") +
    labs(x = "Condition") +
    theme_minimal() +
    theme(
        legend.position = "none"
    )
```

```{r}
sem_df |>
    mutate("cond" = as.factor(cond)) |>
    group_by(implementation, model) |>
    mutate(semantic_association = scale(semantic_association)) |>
    ggplot(aes(x = model, y = semantic_association, fill = cond)) +
    # geom_violin() +
    geom_boxplot() +
    scale_fill_manual(
        values = c("blue", "firebrick2", "purple", "orange")
    ) +
    labs(x = "") +
    facet_wrap(. ~ implementation, ncol = 2, scales = "free") +
    theme_minimal() +
    theme(
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

Difference from baseline
```{r}
sem_df |>
    mutate("cond" = as.factor(cond)) |>
    group_by(implementation, model, scenario) |>
    mutate(
        diff_from_baseline = `semantic_association` - `semantic_association`[cond == 1]
    ) |>
    ungroup() |>
    filter(cond != 1) |>
    group_by(implementation, model, cond) |>
    summarize(
        "mean" = mean(diff_from_baseline, na.rm = TRUE),
        "sd" = sd(diff_from_baseline, na.rm = TRUE),
        "max" = max(diff_from_baseline, na.rm = TRUE),
        "min" = min(diff_from_baseline, na.rm = TRUE)
    )
```


```{r}
sem_df |>
    mutate("cond" = as.factor(cond)) |>
    group_by(implementation, model, scenario) |>
    mutate(
        diff_from_baseline = `semantic_association` - `semantic_association`[cond == 1]
    ) |>
    ungroup() |>
    filter(cond != 1) |>
    group_by(implementation, model) |>
    mutate(diff_from_baseline = scale(diff_from_baseline)) |>
    ggplot(aes(x = model, y = diff_from_baseline, fill = cond)) +
    # geom_violin() +
    geom_boxplot() +
    scale_fill_manual(
        values = c("firebrick2", "purple", "orange")
    ) +
    labs(x = "") +
    facet_wrap(. ~ implementation, scales = "free") +
    theme_minimal() +
    theme(
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

## 

## Semantic association in specific scenarios
```{r}
sem_df |>
    filter(scenario == 56) |>
    select(target, model, implementation, semantic_association)
```

```{r}
scenario_number <- 27

sem_df |>
    group_by(implementation, model) |>
    mutate(
        sem_s = scale(semantic_association),
        implementation_model = paste(implementation, model, sep = " : "),
        context_target = paste(context, target, sep = "..."),
    ) |>
    mutate(cond_sentence = paste(cond, context_target, sep = ": ")) |>
    ungroup() |>
    filter(scenario == scenario_number) |>
    ggplot(aes(x = implementation_model, y = cond_sentence, fill = sem_s)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(
        low = "blue3", high = "red2", mid = "thistle1",
        na.value = "grey",
        midpoint = 0, , limit = c(-5, 5)
    ) +
    labs(y = "", x = "", fill = "semantic association") +
    theme_classic() +
    theme(
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)
    ) +
    theme(aspect.ratio = .5)

sem_df |>
    filter(scenario == scenario_number) |>
    select(sentences, cond)
pull(sentences) |>
    unique()
```